// CY 分流覆写 v1.0 — Clash APP (clash.md)
// Author: ChungyuCheung | Updated: 2026-09-06
// 来源: Shadowrocket/cy.conf v5 (9eb18d00d14497dd47d7894d447d6d8b59c39082)
// 用途: 应用于 NovixLink 等已有配置，无需填写或修改节点订阅。
// 使用: 高级覆写 -> 脚本 -> 管理本地脚本 -> + -> URL 导入本文件，
// 保存脚本，返回高级覆写选中本脚本并保存，使用规则模式启动。
// 保留现有 proxies / proxy-providers / DNS / TUN 和其他设置；
// 保留原策略组以免其他字段引用失效，新增 CY 前缀组，替换运行时 rules。
// MEXC 菲律宾、Bybit 台湾、PayPal 英国测速；AI/海外走 CY 节点选择。
// 自动从当前配置的节点及 providers 筛选；空组 REJECT，地区组没有节点时对应业务不可用。
// include-all 不导入原策略组，原节点名称必须包含对应地区标识。
// Apple、国内、原 skip-proxy 自定义域名直连；广告拦截默认关闭。
// 用代理分流前的 UDP/443 拒绝规则近似 block-quic=all-proxy，不是精准协议检测。
// 未转换 MITM / STUN 响应伪装 / UDP不支持回退开关 / 系统旁路字段。
// 本脚本只迁移分流；当前配置的 DNS、IPv6、TUN 仍按已有配置运行。
// URL 导入会下载本地副本；仓库脚本更新后可重新导入。
// 切回“标准”模式可恢复原配置的分流方式。

function main(config) {
  if (!config || typeof config !== "object" || Array.isArray(config)) {
    throw new Error("CY: 配置对象无效");
  }
  const nodes = Array.isArray(config.proxies) ? config.proxies : [];
  const sources = config["proxy-providers"] || {};
  if (!nodes.length && !Object.keys(sources).length) {
    throw new Error("CY: 当前配置没有节点，请在已有节点的 NovixLink 配置中使用本脚本");
  }
  const groups = [
  {
    "name": "CY 节点选择",
    "type": "select",
    "exclude-filter": "(?i)(剩余|剩餘|流量|到期|官网|官網|套餐|重置|公告|客服|traffic|expire|remaining|reset)",
    "empty-fallback": "REJECT",
    "include-all": true
  },
  {
    "name": "CY 🇵🇭 菲律宾最快",
    "type": "url-test",
    "url": "https://www.gstatic.com/generate_204",
    "interval": 600,
    "timeout": 5000,
    "tolerance": 50,
    "filter": "(?i)^.*(🇵🇭|菲律宾|菲律賓|马尼拉|馬尼拉|宿务|宿霧|\\b((PH|PHL|MNL|CEB|Philippines|Manila|Cebu)([-_ ]?[0-9]+)?)\\b).*$",
    "exclude-filter": "(?i)(剩余|剩餘|流量|到期|官网|官網|套餐|重置|公告|客服|traffic|expire|remaining|reset)",
    "empty-fallback": "REJECT",
    "include-all": true
  },
  {
    "name": "CY 🇹🇼 台湾最快",
    "type": "url-test",
    "url": "https://www.gstatic.com/generate_204",
    "interval": 600,
    "timeout": 5000,
    "tolerance": 50,
    "filter": "(?i)^.*(🇹🇼|台湾|台灣|臺灣|台北|臺北|台中|臺中|高雄|新北|桃园|桃園|\\b((TW|TWN|TPE|TSA|KHH|Taiwan|Taipei|Taichung|Kaohsiung)([-_ ]?[0-9]+)?)\\b).*$",
    "exclude-filter": "(?i)(剩余|剩餘|流量|到期|官网|官網|套餐|重置|公告|客服|traffic|expire|remaining|reset)",
    "empty-fallback": "REJECT",
    "include-all": true
  },
  {
    "name": "CY 🇬🇧 英国最快",
    "type": "url-test",
    "url": "https://www.gstatic.com/generate_204",
    "interval": 600,
    "timeout": 5000,
    "tolerance": 50,
    "filter": "(?i)^.*(🇬🇧|英国|英國|伦敦|倫敦|曼彻斯特|曼徹斯特|\\b((UK|GB|GBR|LHR|LGW|MAN|London|Manchester)([-_ ]?[0-9]+)?|United Kingdom|Britain)\\b).*$",
    "exclude-filter": "(?i)(剩余|剩餘|流量|到期|官网|官網|套餐|重置|公告|客服|traffic|expire|remaining|reset)",
    "empty-fallback": "REJECT",
    "include-all": true
  }
];
  const providers = {
  "CY-Apple": {
    "type": "http",
    "behavior": "classical",
    "format": "text",
    "url": "https://testingcf.jsdelivr.net/gh/blackmatrix7/ios_rule_script@release/rule/Clash/Apple/Apple.list",
    "path": "./rules/cy-Apple.list",
    "interval": 86400
  },
  "CY-ChinaMax": {
    "type": "http",
    "behavior": "classical",
    "format": "text",
    "url": "https://testingcf.jsdelivr.net/gh/blackmatrix7/ios_rule_script@release/rule/Clash/ChinaMax/ChinaMax.list",
    "path": "./rules/cy-ChinaMax.list",
    "interval": 86400
  },
  "CY-Global": {
    "type": "http",
    "behavior": "classical",
    "format": "text",
    "url": "https://testingcf.jsdelivr.net/gh/blackmatrix7/ios_rule_script@release/rule/Clash/Global/Global.list",
    "path": "./rules/cy-Global.list",
    "interval": 86400
  }
};
  const rules = [
  "DOMAIN,localhost,DIRECT",
  "DOMAIN,sequoia.apple.com,DIRECT",
  "DOMAIN,seed-sequoia.siri.apple.com,DIRECT",
  "DOMAIN-SUFFIX,local,DIRECT",
  "DOMAIN-SUFFIX,lan,DIRECT",
  "DOMAIN-SUFFIX,internal,DIRECT",
  "DOMAIN-SUFFIX,ls.apple.com,DIRECT",
  "DOMAIN-SUFFIX,huitone.com,DIRECT",
  "DOMAIN-SUFFIX,huinor.com,DIRECT",
  "DOMAIN-SUFFIX,synology.me,DIRECT",
  "DOMAIN,register.appattest.apple.com,DIRECT",
  "DOMAIN,captive.apple.com,DIRECT",
  "DOMAIN-SUFFIX,ls.apple.com,DIRECT",
  "DOMAIN-SUFFIX,mesu.apple.com,DIRECT",
  "DOMAIN-SUFFIX,swscan.apple.com,DIRECT",
  "DOMAIN-SUFFIX,gdmf.apple.com,DIRECT",
  "DOMAIN-SUFFIX,ocsp.apple.com,DIRECT",
  "DOMAIN-SUFFIX,ess.apple.com,DIRECT",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,mexc.com)),REJECT",
  "DOMAIN-SUFFIX,mexc.com,CY 🇵🇭 菲律宾最快",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,mexc.link)),REJECT",
  "DOMAIN-SUFFIX,mexc.link,CY 🇵🇭 菲律宾最快",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,mexc.app)),REJECT",
  "DOMAIN-SUFFIX,mexc.app,CY 🇵🇭 菲律宾最快",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,mexc.live)),REJECT",
  "DOMAIN-SUFFIX,mexc.live,CY 🇵🇭 菲律宾最快",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,mexc.zone)),REJECT",
  "DOMAIN-SUFFIX,mexc.zone,CY 🇵🇭 菲律宾最快",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,mxc.com)),REJECT",
  "DOMAIN-SUFFIX,mxc.com,CY 🇵🇭 菲律宾最快",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,mxc.ai)),REJECT",
  "DOMAIN-SUFFIX,mxc.ai,CY 🇵🇭 菲律宾最快",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,mexc-api.com)),REJECT",
  "DOMAIN-SUFFIX,mexc-api.com,CY 🇵🇭 菲律宾最快",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,mexcapi.com)),REJECT",
  "DOMAIN-SUFFIX,mexcapi.com,CY 🇵🇭 菲律宾最快",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,mexccdn.com)),REJECT",
  "DOMAIN-SUFFIX,mexccdn.com,CY 🇵🇭 菲律宾最快",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,mxcapi.com)),REJECT",
  "DOMAIN-SUFFIX,mxcapi.com,CY 🇵🇭 菲律宾最快",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-KEYWORD,mexc)),REJECT",
  "DOMAIN-KEYWORD,mexc,CY 🇵🇭 菲律宾最快",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,bybit.com)),REJECT",
  "DOMAIN-SUFFIX,bybit.com,CY 🇹🇼 台湾最快",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,bybit.global)),REJECT",
  "DOMAIN-SUFFIX,bybit.global,CY 🇹🇼 台湾最快",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,bybit.biz)),REJECT",
  "DOMAIN-SUFFIX,bybit.biz,CY 🇹🇼 台湾最快",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,bybit.cloud)),REJECT",
  "DOMAIN-SUFFIX,bybit.cloud,CY 🇹🇼 台湾最快",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,bybit-global.com)),REJECT",
  "DOMAIN-SUFFIX,bybit-global.com,CY 🇹🇼 台湾最快",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,bybitglobal.com)),REJECT",
  "DOMAIN-SUFFIX,bybitglobal.com,CY 🇹🇼 台湾最快",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,bytick.com)),REJECT",
  "DOMAIN-SUFFIX,bytick.com,CY 🇹🇼 台湾最快",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,bybit.nl)),REJECT",
  "DOMAIN-SUFFIX,bybit.nl,CY 🇹🇼 台湾最快",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,bybit.tr)),REJECT",
  "DOMAIN-SUFFIX,bybit.tr,CY 🇹🇼 台湾最快",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,bybit-tr.com)),REJECT",
  "DOMAIN-SUFFIX,bybit-tr.com,CY 🇹🇼 台湾最快",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,bybit.kz)),REJECT",
  "DOMAIN-SUFFIX,bybit.kz,CY 🇹🇼 台湾最快",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,bybitgeorgia.ge)),REJECT",
  "DOMAIN-SUFFIX,bybitgeorgia.ge,CY 🇹🇼 台湾最快",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,bybit.ae)),REJECT",
  "DOMAIN-SUFFIX,bybit.ae,CY 🇹🇼 台湾最快",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,bybit.eu)),REJECT",
  "DOMAIN-SUFFIX,bybit.eu,CY 🇹🇼 台湾最快",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,bybit.id)),REJECT",
  "DOMAIN-SUFFIX,bybit.id,CY 🇹🇼 台湾最快",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,byhkbit.com)),REJECT",
  "DOMAIN-SUFFIX,byhkbit.com,CY 🇹🇼 台湾最快",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,byapis.com)),REJECT",
  "DOMAIN-SUFFIX,byapis.com,CY 🇹🇼 台湾最快",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,bycsi.com)),REJECT",
  "DOMAIN-SUFFIX,bycsi.com,CY 🇹🇼 台湾最快",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,bycbe.com)),REJECT",
  "DOMAIN-SUFFIX,bycbe.com,CY 🇹🇼 台湾最快",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,bymj.io)),REJECT",
  "DOMAIN-SUFFIX,bymj.io,CY 🇹🇼 台湾最快",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,byffbb.com)),REJECT",
  "DOMAIN-SUFFIX,byffbb.com,CY 🇹🇼 台湾最快",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,bybit-aws.com)),REJECT",
  "DOMAIN-SUFFIX,bybit-aws.com,CY 🇹🇼 台湾最快",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,bybdc6.com)),REJECT",
  "DOMAIN-SUFFIX,bybdc6.com,CY 🇹🇼 台湾最快",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,byabcde.com)),REJECT",
  "DOMAIN-SUFFIX,byabcde.com,CY 🇹🇼 台湾最快",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,byapps.net)),REJECT",
  "DOMAIN-SUFFIX,byapps.net,CY 🇹🇼 台湾最快",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,byd3c3.com)),REJECT",
  "DOMAIN-SUFFIX,byd3c3.com,CY 🇹🇼 台湾最快",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,bybits.org)),REJECT",
  "DOMAIN-SUFFIX,bybits.org,CY 🇹🇼 台湾最快",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN,bybit-exchange.github.io)),REJECT",
  "DOMAIN,bybit-exchange.github.io,CY 🇹🇼 台湾最快",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN,bybit.ada.support)),REJECT",
  "DOMAIN,bybit.ada.support,CY 🇹🇼 台湾最快",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-KEYWORD,bybit)),REJECT",
  "DOMAIN-KEYWORD,bybit,CY 🇹🇼 台湾最快",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-KEYWORD,bytick)),REJECT",
  "DOMAIN-KEYWORD,bytick,CY 🇹🇼 台湾最快",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,paypal.com)),REJECT",
  "DOMAIN-SUFFIX,paypal.com,CY 🇬🇧 英国最快",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,paypalobjects.com)),REJECT",
  "DOMAIN-SUFFIX,paypalobjects.com,CY 🇬🇧 英国最快",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,paypal.me)),REJECT",
  "DOMAIN-SUFFIX,paypal.me,CY 🇬🇧 英国最快",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,chatgpt.com)),REJECT",
  "DOMAIN-SUFFIX,chatgpt.com,CY 节点选择",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,openai.com)),REJECT",
  "DOMAIN-SUFFIX,openai.com,CY 节点选择",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,openaiapi.com)),REJECT",
  "DOMAIN-SUFFIX,openaiapi.com,CY 节点选择",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,oaiusercontent.com)),REJECT",
  "DOMAIN-SUFFIX,oaiusercontent.com,CY 节点选择",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,oaistatic.com)),REJECT",
  "DOMAIN-SUFFIX,oaistatic.com,CY 节点选择",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,sora.com)),REJECT",
  "DOMAIN-SUFFIX,sora.com,CY 节点选择",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,ai.com)),REJECT",
  "DOMAIN-SUFFIX,ai.com,CY 节点选择",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,anthropic.com)),REJECT",
  "DOMAIN-SUFFIX,anthropic.com,CY 节点选择",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,claude.ai)),REJECT",
  "DOMAIN-SUFFIX,claude.ai,CY 节点选择",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,claudeusercontent.com)),REJECT",
  "DOMAIN-SUFFIX,claudeusercontent.com,CY 节点选择",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,gemini.google.com)),REJECT",
  "DOMAIN-SUFFIX,gemini.google.com,CY 节点选择",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,aistudio.google.com)),REJECT",
  "DOMAIN-SUFFIX,aistudio.google.com,CY 节点选择",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,makersuite.google.com)),REJECT",
  "DOMAIN-SUFFIX,makersuite.google.com,CY 节点选择",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,notebooklm.google.com)),REJECT",
  "DOMAIN-SUFFIX,notebooklm.google.com,CY 节点选择",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,generativelanguage.googleapis.com)),REJECT",
  "DOMAIN-SUFFIX,generativelanguage.googleapis.com,CY 节点选择",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,proactivebackend-pa.googleapis.com)),REJECT",
  "DOMAIN-SUFFIX,proactivebackend-pa.googleapis.com,CY 节点选择",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,alkalimena-pa.clients6.google.com)),REJECT",
  "DOMAIN-SUFFIX,alkalimena-pa.clients6.google.com,CY 节点选择",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,x.ai)),REJECT",
  "DOMAIN-SUFFIX,x.ai,CY 节点选择",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,grok.com)),REJECT",
  "DOMAIN-SUFFIX,grok.com,CY 节点选择",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN,copilot.microsoft.com)),REJECT",
  "DOMAIN,copilot.microsoft.com,CY 节点选择",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,githubcopilot.com)),REJECT",
  "DOMAIN-SUFFIX,githubcopilot.com,CY 节点选择",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,github.com)),REJECT",
  "DOMAIN-SUFFIX,github.com,CY 节点选择",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,githubusercontent.com)),REJECT",
  "DOMAIN-SUFFIX,githubusercontent.com,CY 节点选择",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,perplexity.ai)),REJECT",
  "DOMAIN-SUFFIX,perplexity.ai,CY 节点选择",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,poe.com)),REJECT",
  "DOMAIN-SUFFIX,poe.com,CY 节点选择",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,quora.com)),REJECT",
  "DOMAIN-SUFFIX,quora.com,CY 节点选择",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,cursor.com)),REJECT",
  "DOMAIN-SUFFIX,cursor.com,CY 节点选择",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,cursor.sh)),REJECT",
  "DOMAIN-SUFFIX,cursor.sh,CY 节点选择",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,cursorapi.com)),REJECT",
  "DOMAIN-SUFFIX,cursorapi.com,CY 节点选择",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,huggingface.co)),REJECT",
  "DOMAIN-SUFFIX,huggingface.co,CY 节点选择",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,hf.co)),REJECT",
  "DOMAIN-SUFFIX,hf.co,CY 节点选择",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,hf.space)),REJECT",
  "DOMAIN-SUFFIX,hf.space,CY 节点选择",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,cdn-lfs.huggingface.co)),REJECT",
  "DOMAIN-SUFFIX,cdn-lfs.huggingface.co,CY 节点选择",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,mistral.ai)),REJECT",
  "DOMAIN-SUFFIX,mistral.ai,CY 节点选择",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,meta.ai)),REJECT",
  "DOMAIN-SUFFIX,meta.ai,CY 节点选择",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,you.com)),REJECT",
  "DOMAIN-SUFFIX,you.com,CY 节点选择",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,phind.com)),REJECT",
  "DOMAIN-SUFFIX,phind.com,CY 节点选择",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,character.ai)),REJECT",
  "DOMAIN-SUFFIX,character.ai,CY 节点选择",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,replicate.com)),REJECT",
  "DOMAIN-SUFFIX,replicate.com,CY 节点选择",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,together.ai)),REJECT",
  "DOMAIN-SUFFIX,together.ai,CY 节点选择",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,cohere.com)),REJECT",
  "DOMAIN-SUFFIX,cohere.com,CY 节点选择",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,groq.com)),REJECT",
  "DOMAIN-SUFFIX,groq.com,CY 节点选择",
  "AND,((NETWORK,udp),(DST-PORT,443),(DOMAIN-SUFFIX,fireworks.ai)),REJECT",
  "DOMAIN-SUFFIX,fireworks.ai,CY 节点选择",
  "DOMAIN-SUFFIX,local,DIRECT",
  "DOMAIN-SUFFIX,lan,DIRECT",
  "DOMAIN-SUFFIX,internal,DIRECT",
  "IP-CIDR,0.0.0.0/8,DIRECT,no-resolve",
  "IP-CIDR,10.0.0.0/8,DIRECT,no-resolve",
  "IP-CIDR,100.64.0.0/10,DIRECT,no-resolve",
  "IP-CIDR,127.0.0.0/8,DIRECT,no-resolve",
  "IP-CIDR,169.254.0.0/16,DIRECT,no-resolve",
  "IP-CIDR,172.16.0.0/12,DIRECT,no-resolve",
  "IP-CIDR,192.0.0.0/24,DIRECT,no-resolve",
  "IP-CIDR,192.0.2.0/24,DIRECT,no-resolve",
  "IP-CIDR,192.88.99.0/24,DIRECT,no-resolve",
  "IP-CIDR,192.168.0.0/16,DIRECT,no-resolve",
  "IP-CIDR,198.18.0.0/15,DIRECT,no-resolve",
  "IP-CIDR,198.51.100.0/24,DIRECT,no-resolve",
  "IP-CIDR,203.0.113.0/24,DIRECT,no-resolve",
  "IP-CIDR,216.36.82.250/32,DIRECT",
  "IP-CIDR,224.0.0.0/4,DIRECT,no-resolve",
  "IP-CIDR,255.255.255.255/32,DIRECT,no-resolve",
  "IP-CIDR6,::1/128,DIRECT,no-resolve",
  "IP-CIDR6,fc00::/7,DIRECT,no-resolve",
  "IP-CIDR6,fe80::/10,DIRECT,no-resolve",
  "RULE-SET,CY-Apple,DIRECT",
  "RULE-SET,CY-ChinaMax,DIRECT",
  "AND,((NETWORK,udp),(DST-PORT,443),(RULE-SET,CY-Global)),REJECT",
  "RULE-SET,CY-Global,CY 节点选择",
  "GEOIP,CN,DIRECT",
  "AND,((NETWORK,udp),(DST-PORT,443)),REJECT",
  "MATCH,CY 节点选择"
];
  const names = groups.map(function (g) { return g.name; });
  nodes.forEach(function (node) {
    if (node && names.indexOf(node.name) !== -1) {
      throw new Error("CY: 节点名称与 CY 策略组冲突，请重命名节点: " + node.name);
    }
  });
  const existing = Array.isArray(config["proxy-groups"]) ? config["proxy-groups"] : [];
  config["proxy-groups"] = existing.filter(function (g) {
    return names.indexOf(g.name) === -1;
  }).concat(groups);
  config["rule-providers"] = Object.assign({}, config["rule-providers"] || {}, providers);
  config.rules = rules;
  config.mode = "rule";
  return config;
}
